{
	"version": 1566327598,
	"fileList": [
		"data.js",
		"game.html",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/dado-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/amarelohorizont-sheet0.png",
		"images/azulhorizont-sheet0.png",
		"images/verdehorizonte-sheet0.png",
		"images/pino-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}